dataset: HCC_Surveillance/derivatives/10_T1_dataset
saving_name: HCC_Surveillance_Tversky_alpha_0.1_beta_0.9
wandb_project_name: HCC Surveillance Liver Tumor Segmentation
model_path_list:
- null
- null
- null
- null
- null
save_plot: false
load_previous_model_params: false
num_workers: 0
foreground_patches: 1
background_patches: 1
patch_samples: 10
post_trans_threshold: 0.5
overlap: 0.5
lr_scheduler: cosine
alpha: 0.1
beta: 0.9
log_freq_gradients: 100
pixel_resampling_size:
- 0.593785
- 0.593785
- 3.0
patch_size:
- 64
- 64
- 16
sliding_window_inf_mode: gaussian
sliding_window_sigma_scale:
- 0.25
- 0.25
- 0.25
early_stopping: 1000
train_batch_size: 2
val_batch_size: 1
learning_rate: 1e-4
max_epochs: 3000
check_point_rate: 200
val_interval: 100
model_type: unet
model_params:
  spatial_dims: 3
  in_channels: 4
  out_channels: 1
  channels:
  - 32
  - 64
  - 128
  - 256
  - 320
  - 320
  strides:
  - 2
  - 2
  - 2
  - 2
  - 1
contrast_gamma:
- 1.0
- 1.5