saving_name: LiTS_pretraining_Tversky_alpha_0.5_beta_0.5
wandb_project_name: 'LiTS liver tumors segmentation'
alpha: 0.5
background_patches: 10
beta: 0.5
check_point_rate: 100
dataset: LiTS/derivatives/Dataset_liver_extracted
early_stopping: 500
foreground_patches: 1
learning_rate: 1e-4
load_previous_model_params: false
log_freq_gradients: 100
lr_scheduler: cosine
max_epochs: 6000
model_params:
  channels:
  - 32
  - 64
  - 128
  - 256
  - 320
  - 320
  in_channels: 4
  out_channels: 1
  spatial_dims: 3
  strides:
  - 2
  - 2
  - 2
  - 2
  - 1
model_path: None
model_type: unet
model_path_list:
- null
- null
- null
- null
- null
num_workers: 0
overlap: 0.5
patch_samples: 10
patch_size:
- 128
- 128
- 16
pixel_resampling_size:
- 0.79
- 0.79
- 1
post_trans_threshold: 0.5
padding_mode: circular
save_plot: false
test_files: []
train_batch_size: 2
train_files:
- volume-0.nii.gz
- volume-1.nii.gz
- volume-2.nii.gz
- volume-3.nii.gz
- volume-4.nii.gz
- volume-5.nii.gz
- volume-6.nii.gz
- volume-7.nii.gz
- volume-8.nii.gz
- volume-9.nii.gz
- volume-10.nii.gz
- volume-11.nii.gz
- volume-12.nii.gz
- volume-13.nii.gz
- volume-14.nii.gz
- volume-15.nii.gz
- volume-16.nii.gz
- volume-17.nii.gz
- volume-18.nii.gz
- volume-19.nii.gz
- volume-20.nii.gz
- volume-21.nii.gz
- volume-22.nii.gz
- volume-23.nii.gz
- volume-24.nii.gz
- volume-25.nii.gz
- volume-26.nii.gz
- volume-27.nii.gz
- volume-28.nii.gz
- volume-29.nii.gz
- volume-30.nii.gz
- volume-31.nii.gz
- volume-32.nii.gz
- volume-33.nii.gz
- volume-34.nii.gz
- volume-35.nii.gz
- volume-36.nii.gz
- volume-37.nii.gz
- volume-38.nii.gz
- volume-39.nii.gz
- volume-40.nii.gz
- volume-41.nii.gz
- volume-42.nii.gz
- volume-43.nii.gz
- volume-44.nii.gz
- volume-45.nii.gz
- volume-46.nii.gz
- volume-47.nii.gz
- volume-48.nii.gz
- volume-49.nii.gz
- volume-50.nii.gz
- volume-51.nii.gz
- volume-52.nii.gz
- volume-53.nii.gz
- volume-54.nii.gz
- volume-55.nii.gz
- volume-56.nii.gz
- volume-57.nii.gz
- volume-58.nii.gz
- volume-59.nii.gz
- volume-60.nii.gz
- volume-61.nii.gz
- volume-62.nii.gz
- volume-63.nii.gz
- volume-64.nii.gz
- volume-65.nii.gz
- volume-66.nii.gz
- volume-67.nii.gz
- volume-68.nii.gz
- volume-69.nii.gz
- volume-70.nii.gz
- volume-71.nii.gz
- volume-72.nii.gz
- volume-73.nii.gz
- volume-74.nii.gz
- volume-75.nii.gz
- volume-76.nii.gz
- volume-77.nii.gz
- volume-78.nii.gz
- volume-79.nii.gz
- volume-80.nii.gz
- volume-81.nii.gz
- volume-82.nii.gz
- volume-83.nii.gz
- volume-84.nii.gz
- volume-85.nii.gz
- volume-86.nii.gz
- volume-87.nii.gz
- volume-88.nii.gz
- volume-89.nii.gz
- volume-90.nii.gz
- volume-91.nii.gz
- volume-92.nii.gz
- volume-93.nii.gz
- volume-94.nii.gz
- volume-95.nii.gz
- volume-96.nii.gz
- volume-97.nii.gz
- volume-98.nii.gz
- volume-99.nii.gz
- volume-100.nii.gz
- volume-101.nii.gz
- volume-102.nii.gz
- volume-103.nii.gz
- volume-104.nii.gz
val_batch_size: 1
val_files:
- volume-105.nii.gz
- volume-106.nii.gz
- volume-107.nii.gz
- volume-108.nii.gz
- volume-109.nii.gz
- volume-110.nii.gz
- volume-111.nii.gz
- volume-112.nii.gz
- volume-113.nii.gz
- volume-114.nii.gz
- volume-115.nii.gz
- volume-116.nii.gz
- volume-117.nii.gz
- volume-118.nii.gz
- volume-119.nii.gz
- volume-120.nii.gz
- volume-121.nii.gz
- volume-122.nii.gz
- volume-123.nii.gz
- volume-124.nii.gz
- volume-125.nii.gz
- volume-126.nii.gz
- volume-127.nii.gz
- volume-128.nii.gz
- volume-129.nii.gz
- volume-130.nii.gz
val_interval: 100
sliding_window_inf_mode: gaussian
sliding_window_sigma_scale:
- 0.25
- 0.25
- 0.25
