alpha: 0.1
background_patches: 10
beta: 0.9
check_point_rate: 100
dataset: LLD_MMRI/derivatives/9_T1_dataset_all_lesions
early_stopping: 500
foreground_patches: 1
learning_rate: 1e-4
load_previous_model_params: false
log_freq_gradients: 100
lr_scheduler: cosine
max_epochs: 6000

model_params:
  channels:
  - 32
  - 64
  - 128
  - 256
  - 320
  - 320
  in_channels: 4
  out_channels: 1
  spatial_dims: 3
  strides:
  - 2
  - 2
  - 2
  - 2
  - 1
model_path_list:
- wandb/model_fold_0/files/last_checkpoint.pth.gz
model_type: unet
num_workers: 0
overlap: 0.5
patch_samples: 10
patch_size:
- 128
- 128
- 16
pixel_resampling_size:
- 1
- 1
- 1
post_trans_threshold: 0.5
save_plot: false
seed: 42
train_batch_size: 2
val_batch_size: 1
val_interval: 50
saving_name: LLD_MMRI_finetuning_Tversky_alpha_0.1_beta_0.9
sliding_window_inf_mode: gaussian
sliding_window_sigma_scale:
- 0.25
- 0.25
- 0.25

